package proyectosisex;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jpl7.Atom;
import org.jpl7.Query;
import org.jpl7.Term;
import org.jpl7.Variable;

/**
 *
 * @author Alfredo
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ico.png")));

        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(true);
        String pasostr = CargarDatos();

        jTextPaneTipo.setEnabled(false);

        jTextPaneDisponibleEn.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelHorario = new javax.swing.JLabel();
        jComboBoxServcio = new javax.swing.JComboBox<>();
        jLabelTipoDieta = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jButtonConsultar = new javax.swing.JButton();
        jLabelTipoDieta1 = new javax.swing.JLabel();
        jLabelTipoDieta2 = new javax.swing.JLabel();
        jComboBoxEstrenoPelicula = new javax.swing.JComboBox<>();
        jLabelTipoDieta3 = new javax.swing.JLabel();
        jComboBoxDuracionPeli = new javax.swing.JComboBox<>();
        jComboBoxDuracionEpi = new javax.swing.JComboBox<>();
        jLabelTipoDieta4 = new javax.swing.JLabel();
        jComboBoxEstudios = new javax.swing.JComboBox<>();
        jLabelTipoDieta5 = new javax.swing.JLabel();
        jComboBoxEstrenoSerie = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelImgPelicula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneTipo = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneDisponibleEn = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneActores = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPanelTiulo = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPaneDuracion = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneClasificacion = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema experto peliculas y series");
        setBackground(java.awt.SystemColor.control);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("inicioFrm"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Tipo:");

        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jLabelHorario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHorario.setText("Servicio Streaming:");

        jComboBoxServcio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Netflix", "Amazon" }));
        jComboBoxServcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServcioActionPerformed(evt);
            }
        });

        jLabelTipoDieta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta.setText("Estudio cinematográfico preferido:");
        jLabelTipoDieta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jComboBoxGenero.setEnabled(false);
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        jButtonConsultar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonConsultar.setText("Consultar");
        jButtonConsultar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConsultar.setEnabled(false);
        jButtonConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConsultarMouseClicked(evt);
            }
        });
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelTipoDieta1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta1.setText("Duración por capitulo:");

        jLabelTipoDieta2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta2.setText("Duración pelicula:");

        jComboBoxEstrenoPelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000-2008", "2008-2016", "2016-2022" }));
        jComboBoxEstrenoPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstrenoPeliculaActionPerformed(evt);
            }
        });

        jLabelTipoDieta3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta3.setText("Estreno pelicula:");

        jComboBoxDuracionPeli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal (1 hr - 2 hr)", "Media (2 hr - 3 hr)", "Larga (> 3 hr)" }));
        jComboBoxDuracionPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDuracionPeliActionPerformed(evt);
            }
        });

        jComboBoxDuracionEpi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal (45 m - 1hr)", "Media (1 hr - 1 hr 30m)", "Larga (1 hr 30m - 2 hr)" }));
        jComboBoxDuracionEpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDuracionEpiActionPerformed(evt);
            }
        });

        jLabelTipoDieta4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta4.setText("Genero:");

        jComboBoxEstudios.setEnabled(false);
        jComboBoxEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstudiosActionPerformed(evt);
            }
        });

        jLabelTipoDieta5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDieta5.setText("Estreno serie:");

        jComboBoxEstrenoSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2005", "2018", "2019", "2020", "2021" }));
        jComboBoxEstrenoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstrenoSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTipoDieta4)
                    .addComponent(jLabelTipoDieta))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEstudios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxServcio, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipoDieta1)
                    .addComponent(jLabelTipoDieta2)
                    .addComponent(jLabelTipoDieta3)
                    .addComponent(jLabelTipoDieta5))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDuracionEpi, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDuracionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstrenoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstrenoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHorario)
                    .addComponent(jLabelTipoDieta1)
                    .addComponent(jComboBoxServcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxDuracionEpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoDieta3)
                        .addComponent(jComboBoxEstrenoPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoDieta4)
                            .addComponent(jComboBoxEstrenoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoDieta2)
                            .addComponent(jComboBoxDuracionPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jButtonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoDieta5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoDieta))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabelTipo.getAccessibleContext().setAccessibleName("jLabelTipo");
        jLabelTipoDieta.getAccessibleContext().setAccessibleName("jLabelGenero");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel7.setBackground(java.awt.SystemColor.inactiveCaption);
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peliculas y series");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Titulo:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Duración:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Actores principales:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Disponible en:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Clasificación:");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabelImgPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelImgPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTextPaneTipo.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(jTextPaneTipo);

        jTextPaneDisponibleEn.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTextPaneDisponibleEn);

        jScrollPane5.setViewportView(jTextPaneActores);

        jScrollPane6.setViewportView(jTextPanelTiulo);

        jScrollPane7.setViewportView(jTextPaneDuracion);

        jTextPaneClasificacion.setDragEnabled(true);
        jScrollPane2.setViewportView(jTextPaneClasificacion);

        jLabel9.setBackground(java.awt.SystemColor.inactiveCaption);
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Recomendación");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConsultarMouseClicked
        //JOptionPane.showMessageDialog(rootPane, "Hola");
    }//GEN-LAST:event_jButtonConsultarMouseClicked

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        String tipo = (String) jComboBoxTipo.getSelectedItem();
        String servicio = (String) jComboBoxServcio.getSelectedItem();

        if (tipo != null) {
            jComboBoxGenero.setEnabled(true);
            if (tipo.equals("Pelicula")) {
                jComboBoxDuracionPeli.setEnabled(true);
                jComboBoxDuracionEpi.setEnabled(false);
                jComboBoxEstrenoSerie.setEnabled(false);
                jComboBoxEstrenoPelicula.setEnabled(true);
            } else {

                jComboBoxDuracionPeli.setEnabled(false);
                jComboBoxDuracionEpi.setEnabled(true);
                jComboBoxEstrenoSerie.setEditable(true);
                jComboBoxEstrenoPelicula.setEnabled(false);
            }
            jComboBoxGenero.setEnabled(true);
            //JOptionPane.showMessageDialog(null,seleccionado);
            String t1 = "consult('src/peliculas.pl')";
            Query q1 = new Query(t1);
            System.out.println(t1 + " " + (q1.hasSolution() ? "verdadero" : "fallo"));

            Variable GENERO = new Variable("GENERO");

            Query q4
                    = new Query(
                            "genseriopel",
                            new Term[]{new Atom(servicio.toLowerCase()), new Atom(tipo.toLowerCase()), GENERO}
                    );

            java.util.Map<String, Term>[] solution;

            solution = q4.allSolutions();

            jComboBoxGenero.removeAllItems();

            for (int i = 0; i < solution.length; i++) {
                //JOptionPane.showMessageDialog(null, solution[0].get("G"));

                String item = solution[i].get("GENERO").toString();
                jComboBoxGenero.addItem(item.substring(0, 1).toUpperCase() + item.substring(1).toLowerCase());
            }

        }

    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged

    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        //////////////////////////////////////////////////////////////////////
        //TIPO,OESTUDIO,ESTUDIO
        String t1 = "consult('src/peliculas.pl')";
        Query q1 = new Query(t1);
        System.out.println(t1 + " " + (q1.hasSolution() ? "verdadero" : "fallo"));

        String tipo = (String) jComboBoxTipo.getSelectedItem();

        String servicio = (String) jComboBoxServcio.getSelectedItem();

        String genero = (String) jComboBoxGenero.getSelectedItem();
        if (genero != null) {
            System.out.println(t1 + " " + (q1.hasSolution() ? "verdadero" : "fallo"));

            Variable OESTUDIO = new Variable("OESTUDIO");
            Variable ESTUDIO = new Variable("ESTUDIO");
            Query q
                    = new Query(
                            "consulestudiosp",
                            new Term[]{new Atom(tipo.toLowerCase()), new Atom(genero.toLowerCase()), new Atom(servicio.toLowerCase()), OESTUDIO, ESTUDIO}
                    );

            java.util.Map<String, Term>[] estudios;

            estudios = q.allSolutions();

            jComboBoxEstudios.removeAllItems();

            jComboBoxEstudios.setEnabled(true);

            for (int i = 0; i < estudios.length; i++) {

                String item = estudios[i].get("ESTUDIO").toString().replace("\'", "");
                jComboBoxEstudios.addItem(item);
            }
        }


    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jComboBoxEstrenoPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstrenoPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstrenoPeliculaActionPerformed

    private void jComboBoxDuracionPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDuracionPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDuracionPeliActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed

        String tipo = (String) jComboBoxTipo.getSelectedItem();

        String disponible = (String) jComboBoxServcio.getSelectedItem();

        String genero = (String) jComboBoxGenero.getSelectedItem();

        String[] estreno = jComboBoxEstrenoPelicula.getSelectedItem().toString().split("-");
        String estrenoSerie = jComboBoxEstrenoSerie.getSelectedItem().toString();

        String duracionEpí = (jComboBoxDuracionEpi.getSelectedItem().toString().split("\\("))[0].trim();

        String duracionPel = (jComboBoxDuracionPeli.getSelectedItem().toString().split("\\("))[0].trim();

        String duracion = (String) duracionEpí;

        String estudio = ((String) jComboBoxEstudios.getSelectedItem()).replace(" ", "").toLowerCase();

        String estrenomin = (String) (estreno[0]);
        String estrenomax = (String) (estreno[1]);

        if(tipo.equals("Serie")){
            estrenomax = estrenoSerie;
            estrenomin = estrenoSerie;
        }
        
        if (tipo.equals("Pelicula")) {
            duracion = (String) duracionPel;
        }

        //JOptionPane.showMessageDialog(null, (estreno[0] + "-" + estreno[1] + "-" + duracionEpí + "-" + duracionPel));
        String t1 = "consult('src/peliculas.pl')";
        Query q1 = new Query(t1);
        System.out.println(t1 + " " + (q1.hasSolution() ? "verdadero" : "fallo"));

        Variable TITULO = new Variable("TITULO");
        Variable DURACIONR = new Variable("DURACIONR");
        Variable CLASIFICACIONR = new Variable("CLASIFICACIONR");
        Variable ANIOESTRENOR = new Variable("ANIOESTRENOR");
        Variable ACTORESPRINCIPALESR = new Variable("ACTORESPRINCIPALESR");
        Variable NOMBREIMG = new Variable("NOMBREIMG");

        Atom j = new Atom(estreno[0]);

        Query q4
                = new Query(
                        "recpeliculaoserie",
                        new Term[]{new Atom(tipo.toLowerCase()), new Atom(disponible.toLowerCase()),
                            new Atom(genero.toLowerCase()), new Atom(estudio), new Atom(duracion.toLowerCase()),
                            new Atom(estrenomin), new Atom(estrenomax), TITULO, DURACIONR, CLASIFICACIONR, ANIOESTRENOR, ACTORESPRINCIPALESR, NOMBREIMG}
                );

        java.util.Map<String, Term> solution;

        solution = q4.oneSolution();

        if (solution == null) {
            JOptionPane.showMessageDialog(null, "No existe una reomendación con esos atributos.");
        } else {

            String imagen = solution.get("NOMBREIMG").toString().replace("\'", "");

            ImageIcon imageIcon = new ImageIcon(new ImageIcon("src/imagenes/" + imagen).getImage().getScaledInstance(270, 300, Image.SCALE_DEFAULT));

            jLabelImgPelicula.setIcon(imageIcon);

            jTextPanelTiulo.setText(solution.get("TITULO").toString().replace("\'", ""));

            jTextPaneClasificacion.setText(solution.get("ANIOESTRENOR").toString());

            jTextPaneDisponibleEn.setText(disponible);
            
            jTextPaneDuracion.setText(solution.get("DURACIONR") + " minutos");
            
            jTextPaneClasificacion.setText(solution.get("CLASIFICACIONR").toString().toUpperCase());
            
            jTextPaneActores.setText(solution.get("ACTORESPRINCIPALESR").toString().toUpperCase().replace("\'", "").replace("]", "").replace("[", ""));
            
            //jTextPaneAnioEstreno.setText(solution.get("ANIOESTRENOR").toString());

            jTextPaneTipo.setText(tipo);
        }


    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jComboBoxDuracionEpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDuracionEpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDuracionEpiActionPerformed

    private void jComboBoxEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstudiosActionPerformed
        // TODO add your handling code here:
        jButtonConsultar.setEnabled(true);
    }//GEN-LAST:event_jComboBoxEstudiosActionPerformed

    private void jComboBoxServcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServcioActionPerformed

        String servicio = (String) jComboBoxServcio.getSelectedItem();

        String plarchivo = "consult('src/peliculas.pl')";
        Query con = new Query(plarchivo);
        System.out.println(plarchivo + " " + (con.hasSolution() ? "verdadero" : "fallo"));

        Query existenpeliculasservicio
                = new Query(
                        "existenpeliculasservicio",
                        new Term[]{new Atom(servicio.toLowerCase())}
                );

        boolean existenpeliculasservicioresultado;

        existenpeliculasservicioresultado = existenpeliculasservicio.hasSolution();

        Query existenseriesservicio
                = new Query(
                        "existenseriesservicio",
                        new Term[]{new Atom(servicio.toLowerCase())}
                );

        boolean existenseriesservicioresultado;

        existenseriesservicioresultado = existenseriesservicio.hasSolution();

        jComboBoxTipo.removeAllItems();

        if (existenseriesservicioresultado) {
            jComboBoxTipo.addItem("Serie");
        }

        if (existenpeliculasservicioresultado) {
            jComboBoxTipo.addItem("Pelicula");
        }

        if (existenpeliculasservicioresultado || existenseriesservicioresultado) {
            jComboBoxTipo.setEnabled(true);
        }

    }//GEN-LAST:event_jComboBoxServcioActionPerformed

    private void jComboBoxEstrenoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstrenoSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstrenoSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);

            }
        });

    }

    public static String CargarDatos() {

        String t1 = "consult('src/peliculas.pl')";
        Query q1 = new Query(t1);
        System.out.println(t1 + " " + (q1.hasSolution() ? "verdadero" : "fallo"));

        /*Variable X = new Variable("X");
        Variable X1 = new Variable("X1");

        Query q4
                = new Query(
                        "saludo",
                        new Term[]{new Atom("enrique"), X1}
                );

        java.util.Map<String, Term> solution;

        solution = q4.oneSolution();

        System.out.println("first solution of saludo(Xf)");
        System.out.println("X = " + solution.get("X"));
        System.out.println("first solution of saludo(Xf)");
        System.out.println("X = " + solution.get("X1"));
        
        String[] pasos = solution.get("X1").toString().split(",");*/
        String pasostr = "";
        /*for (String paso : pasos) {
            
            pasostr+=paso.replace(" ", "").replace("]","").replace("[","")+"\n";
        
        }*/
        for (int i = 0; i <= 100; i++) {

            pasostr += "gh" + "\n";

        }

        return pasostr;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox<String> jComboBoxDuracionEpi;
    private javax.swing.JComboBox<String> jComboBoxDuracionPeli;
    private javax.swing.JComboBox<String> jComboBoxEstrenoPelicula;
    private javax.swing.JComboBox<String> jComboBoxEstrenoSerie;
    private javax.swing.JComboBox<String> jComboBoxEstudios;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxServcio;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelImgPelicula;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoDieta;
    private javax.swing.JLabel jLabelTipoDieta1;
    private javax.swing.JLabel jLabelTipoDieta2;
    private javax.swing.JLabel jLabelTipoDieta3;
    private javax.swing.JLabel jLabelTipoDieta4;
    private javax.swing.JLabel jLabelTipoDieta5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPaneActores;
    private javax.swing.JTextPane jTextPaneClasificacion;
    private javax.swing.JTextPane jTextPaneDisponibleEn;
    private javax.swing.JTextPane jTextPaneDuracion;
    private javax.swing.JTextPane jTextPaneTipo;
    private javax.swing.JTextPane jTextPanelTiulo;
    // End of variables declaration//GEN-END:variables
}
